# Generated by Django 4.2.3 on 2023-08-18 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog_home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportedblogpost",
            name="user",
            field=models.ManyToManyField(
                null=True, related_name="reported_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="reportedcomments",
            name="user",
            field=models.ManyToManyField(
                null=True, related_name="reported_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
