# Generated by Django 4.2.3 on 2023-08-18 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog_home", "0002_alter_reportedblogpost_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reportedcomments",
            old_name="post",
            new_name="comment",
        ),
    ]
