# Generated by Django 4.2.3 on 2023-08-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_home", "0005_remove_suggestion_user_suggestion_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="images/"),
        ),
    ]
