# Generated by Django 4.2.3 on 2023-08-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_home", "0006_comments_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="text",
            field=models.CharField(max_length=500),
        ),
    ]
