# Generated by Django 4.2.3 on 2023-08-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_home", "0007_alter_comments_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="attachment",
            field=models.FileField(null=True, upload_to="images/"),
        ),
    ]
