# Generated by Django 4.2.3 on 2023-08-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_home", "0008_alter_comments_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_apprroved",
            field=models.BooleanField(default=False),
        ),
    ]
