# Generated by Django 4.2.3 on 2023-08-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
